export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  RECEPCION: '/recepcion',
  RECEPCION_NUEVA: '/recepcion/nueva',
  RECEPCION_DETALLE: (id: string) => `/recepcion/${id}`,
  PRODUCCION: '/produccion',
  PRODUCCION_NUEVA: '/produccion/nueva',
  PRODUCCION_DETALLE: (id: string) => `/produccion/${id}`,
  ALMACEN: '/almacen',
  ALMACEN_INVENTARIO: '/almacen/inventario',
  ALMACEN_MOVIMIENTOS: '/almacen/movimientos',
  ALMACEN_UBICACIONES: '/almacen/ubicaciones',
  EXPEDICION: '/expedicion',
  EXPEDICION_NUEVA: '/expedicion/nueva',
  EXPEDICION_DETALLE: (id: string) => `/expedicion/${id}`,
  TRAZABILIDAD: '/trazabilidad',
  TRAZABILIDAD_DETALLE: (codigo: string) => `/trazabilidad/${codigo}`,
  ALERTAS: '/alertas',
  ALERTAS_NUEVA: '/alertas/nueva',
  ALERTAS_DETALLE: (id: string) => `/alertas/${id}`,
  REPORTES: '/reportes',
  CONFIGURACION: '/configuracion',
  CONFIGURACION_USUARIOS: '/configuracion/usuarios',
  CONFIGURACION_PRODUCTOS: '/configuracion/productos',
  CONFIGURACION_PROVEEDORES: '/configuracion/proveedores',
  CONFIGURACION_CLIENTES: '/configuracion/clientes',
  CONFIGURACION_ALMACENES: '/configuracion/almacenes',
  CONFIGURACION_LINEAS: '/configuracion/lineas-produccion',
  PERFIL: '/perfil',
  PUBLIC_TRACE: (codigo: string) => `/t/${codigo}`,
} as const;