export const ROLES = {
  ADMINISTRADOR: 'ADMINISTRADOR',
  CALIDAD: 'CALIDAD',
  RECEPCION: 'RECEPCION',
  PRODUCCION: 'PRODUCCION',
  ALMACEN: 'ALMACEN',
  DESPACHO: 'DESPACHO',
  CLIENTE: 'CLIENTE',
  AUTORIDAD: 'AUTORIDAD',
} as const;

export const PERMISSIONS = {
  RECEPCION: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.RECEPCION],
  PRODUCCION: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.PRODUCCION],
  ALMACEN: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.ALMACEN],
  EXPEDICION: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.DESPACHO],
  CONFIGURACION: [ROLES.ADMINISTRADOR],
  ALERTAS: [ROLES.ADMINISTRADOR, ROLES.CALIDAD],
  REPORTES: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.RECEPCION, ROLES.PRODUCCION, ROLES.ALMACEN, ROLES.DESPACHO],
  TRAZABILIDAD: [ROLES.ADMINISTRADOR, ROLES.CALIDAD, ROLES.RECEPCION, ROLES.PRODUCCION, ROLES.ALMACEN, ROLES.DESPACHO, ROLES.CLIENTE, ROLES.AUTORIDAD],
} as const;

export const LOT_STATUS = {
  ACTIVO: 'ACTIVO',
  RESERVADO: 'RESERVADO',
  EN_PRODUCCION: 'EN_PRODUCCION',
  EN_TRANSITO: 'EN_TRANSITO',
  ENTREGADO: 'ENTREGADO',
  VENCIDO: 'VENCIDO',
  BLOQUEADO: 'BLOQUEADO',
  RETIRADO: 'RETIRADO',
  CONSUMIDO: 'CONSUMIDO',
} as const;

export const MOVEMENT_TYPES = {
  RECEPCION: 'RECEPCION',
  PRODUCCION: 'PRODUCCION',
  MOVIMIENTO_INTERNO: 'MOVIMIENTO_INTERNO',
  EXPEDICION: 'EXPEDICION',
  DEVOLUCION: 'DEVOLUCION',
  AJUSTE: 'AJUSTE',
  CONSUMO: 'CONSUMO',
  MERMA: 'MERMA',
} as const;